import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideRouter } from '@angular/router';
import {
  provideLucideIcons,
  LucideBookOpen,
  LucideBuilding2,
  LucideCalendarDays,
  LucideCheck,
  LucideCircleQuestionMark,
  LucideEye,
  LucideEyeOff,
  LucideGraduationCap,
  LucideHouse,
  LucideLock,
  LucideLogIn,
  LucideLogOut,
  LucideMail,
  LucideMailCheck,
  LucideMap,
  LucideMapPin,
  LucideMenu,
  LucideMoon,
  LucidePencil,
  LucidePhone,
  LucidePlus,
  LucideRotateCw,
  LucideShieldCheck,
  LucideSun,
  LucideTrash2,
  LucideUser,
  LucideUsers,
  LucideUtensils,
  LucideX,
} from '@lucide/angular';

import { routes } from './app.routes';
import { authInterceptor } from './core/auth.interceptor';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes),
    provideHttpClient(withInterceptors([authInterceptor])),
    provideLucideIcons(
      LucideBookOpen,
      LucideBuilding2,
      LucideCalendarDays,
      LucideCheck,
      LucideCircleQuestionMark,
      LucideEye,
      LucideEyeOff,
      LucideGraduationCap,
      LucideHouse,
      LucideLock,
      LucideLogIn,
      LucideLogOut,
      LucideMail,
      LucideMailCheck,
      LucideMap,
      LucideMapPin,
      LucideMenu,
      LucideMoon,
      LucidePencil,
      LucidePhone,
      LucidePlus,
      LucideRotateCw,
      LucideShieldCheck,
      LucideSun,
      LucideTrash2,
      LucideUser,
      LucideUsers,
      LucideUtensils,
      LucideX,
    ),
  ]
};
